export { default as Header } from "./header";
export { default as Home } from "./home";
export { default as Routines } from "./routines";
export { default as Activities } from "./activities";
export { default as AuthorizeUser } from "./auth";
export { default as Activity } from "./activity";
export { default as Popup } from "./popup"
export { default as Footer } from "./footer";
export { default as CreateAct } from "./createActivity"
